### ISSUE TITLE
Could not find dependency (linuxdeploy::core::elf_file::DependencyNotFoundError)

### ISSUE THREAD

**Issue by gfrontera** [linuxdeploy/linuxdeploy-plugin-qt#116]
When using current latest releases of `linuxdeploy-x86_64.AppImage` and `linuxdeploy-plugin-qt-x86_64.AppImage`, I get this error when generating an AppImage for my project:
```
-- Running input plugin: qt -- 
[qt/stdout] Using qmake: /usr/bin/qmake 
[qt/stdout] 
[qt/stdout] Using Qt version:  5.12.8  ( 5 ) 
[qt/stderr] terminate called after throwing an instance of 'linuxdeploy::core::elf_file::DependencyNotFoundError'
[qt/stderr]   what():  Could not find dependency: libgraphics_item.so
ERROR: Failed to run plugin: qt (exit code: 127) 
```

The missing library is part of my project. However, when using an [earlier version](https://github.com/linuxdeploy/linuxdeploy/actions/runs/2593818732) of `linuxdeploy-x86_64.AppImage`, it works without any problems. Does the Qt plugin need to be updated to keep in sync with linuxdeploy releases? Can this be a regression?

The command I run (from a GitLab CI job) is:
```
LD_LIBRARY_PATH=/opt/poco-1.11.2/lib APPIMAGE_EXTRACT_AND_RUN=1 ./linuxdeploy-x86_64.AppImage --appdir "${CI_PROJECT_DIR}/${APP_NAME}" -d "App.desktop" -e "${CI_PROJECT_DIR}/build/${APP_BINARY_NAME}" -i "${CI_PROJECT_DIR}/icon.png" --plugin qt --output appimage
```

Thank you.

**Comment by gfrontera** [comment]
It is possible to work around the issue by including the path containing the executable in `LD_LIBRARY_PATH`.

**Comment by TheAssassin** [comment]
Please re-run with `export DEBUG=1` to increase the log verbosity.

In general, those kind of issues are usually due to the lack of a proper `rpath` (`DT_RUNPATH`) set in the files within the AppDir. liblinuxdeploy just uses `ldd` to discover dependencies, and requires either correct `rpath`s (which is the way to go and possible with, e.g., CMake, with just a few additional lines of code), or something like `LD_LIBRARY_PATH` set by the user before the call.
