### ISSUE TITLE
Plugin for aarch64

### ISSUE THREAD

**Issue by awcbantam** [linuxdeploy/linuxdeploy-plugin-qt#120]
I am trying to use this plugin on a raspberry pi but I cannot figure out for the life of me how to build it from source on the pi. Is there some process I should be following. Sorry for the vague question but any advice would be great. My current steps have been to use CmakeTools to build and then try and create an appiamge using linuxdeploy (which I was able to build from source) and appimage toolkit, but that doesnt seem to work. Any suggestions?

I tried reaching out on the freenode channel suggested in the linuxdeploy readme but it seemed pretty dead.

**Comment by TheAssassin** [comment]
I fixed the link, it's been outdated for more than a year. Freenode is dead. Everyone's moved to other networks, mostly Libera.Chat: https://web.libera.chat/#appimage

> CmakeTools

Never heard of.

> Any suggestions?

You need to build linuxdeploy for AArch64 first, however this is not officially supported. See https://github.com/linuxdeploy/linuxdeploy/issues?q=is%3Aissue+is%3Aopen+arm. The reason is a major lack of time.

**Comment by awcbantam** [comment]
I have linuxdeploy built on the pi. It works very well actually, except the final appdir is missing the QML directories. The solution suggested seems to be the linuxdeploy-plugin-qt which is where i'm stuck at now. Is it possible to directly copy my QML directories into the appdir structure and circumvent the plugin?

**Comment by awcbantam** [comment]
Building linuxdeploy-plugin-qt from source on the Pi required me to replace the folder /lib/linuxdeploy inside of the plugin with my already built linuxdeploy directory. After that, the plugin built with no issues.
