### ISSUE TITLE
Qt AppRun hooks appear to be missing required QT environment variables

### ISSUE THREAD

**Issue by mdear** [linuxdeploy/linuxdeploy-plugin-qt#163]
For some reason, Qt environment variables were not set up correctly in the top level AppRun Qt hooks.

After I made the following manual modification (and after manually packaging the Wayland plugins and Wayland platform plugins) the AppImage was able to be run as expected on the target aarch64 device.

As I'm very new to Qt, I don't have enough confidence yet to make this a pull request, but hopefully it will be helpful nevertheless.  

```
ccs@ccs-VirtualBox:~/Downloads/499.dice.AppDir$ cat apprun-hooks/linuxdeploy-plugin-qt-hook.sh 
# generated by linuxdeploy-plugin-qt

# try to make Qt apps more "native looking" on Gtk-based desktops, if possible
# see https://github.com/AppImage/AppImageKit/issues/977#issue-462374883
case "${XDG_CURRENT_DESKTOP}" in
    *GNOME*|*gnome*|*XFCE*)
        export QT_QPA_PLATFORMTHEME=gtk2
        ;;
esac

# Begin modification mdear
QT_BASE_DIR="$(readlink -f "$(dirname "$0")")"
export LD_LIBRARY_PATH=${QT_BASE_DIR}/usr/lib:${QT_BASE_DIR}/lib:${LD_LIBRARY_PATH}
export QT_PLUGIN_PATH=${QT_BASE_DIR}/usr/plugins
export QT_INSTALL_PLUGINS=${QT_PLUGIN_PATH}
export QT_INSTALL_QML=${QT_BASE_DIR}/usr/qml
export QML2_IMPORT_PATH=${QT_INSTALL_QML}
export QML_SOURCES_PATHS=${QT_INSTALL_QML}
export QT_QPA_PLATFORM_PLUGIN_PATH=${QT_PLUGIN_PATH}/platforms
# End modification mdear
```

**Comment by TheAssassin** [comment]
None of these environment variables must be set. In fact, they're counterproductive, as they affect all subprocesses, even calls to software on the base system. This used to be a very annoying problem in the past.

The Qt-specific values are set using a `qt.conf`. `LD_LIBRARY_PATH` is not needed due to linuxdeploy's `DT_RUNPATH` method.

The reason your packaging may have failed is the incomplete deployment of the Wayland plugins which you work around with your modifications. If you added them to a proper deployer in this plugin, it'd work.

**Comment by TheAssassin** [comment]
P.S.: The few variables we set do not harm system processes created as children from your application and have been hand-picked. Even those will be removed in a future release, though, to increase compatibility with Wayland.
