### ISSUE TITLE
Automatically bundle Qt plugin for AppImage updates

### ISSUE THREAD

**Issue by probonopd** [linuxdeploy/linuxdeploy-plugin-qt#34]
`linuxdeploy-plugin-qt` should automatically use `updatedeployqt` so that users must do nothing special to get the update functionality for their Qt apps automatically.

Also see:
https://github.com/TheFutureShell/updatedeployqt/issues/9

**Comment by TheAssassin** [comment]
Not every Qt app has a UI. And it's likely pure bloat for some apps.

Also I don't want to ship random software whose compliance can't be guaranteed. Noone's ever validated for that.

**Comment by probonopd** [comment]
- Re. 1, OK, then let's add a check that this only gets deployed for GUI apps
- Re. 2, it works for me (tm) but feel free to review

**Comment by TheAssassin** [comment]
Works for me != license compliance...

I am not willing to auto-ship random third party software. Also I am not willing to auto-shipping non-Qt plugins to people. Especially not by default. I don't see any use in this.

**Comment by probonopd** [comment]
I do see _use_ in this - every AppImage produced with it would be neatly updateable. 

But I do understand your reservations on _how_ to achieve this.

**Comment by TheAssassin** [comment]
I'm not reluctant to adding a plugin for linuxdeploy to add this. But this is surely an opt-in feature, since it brings new license compliance complexity.

**Comment by probonopd** [comment]
My point is that such functionality should be opt-out not opt-in since all AppImage opt-in stuff never gets useed (think signatures).

**Comment by TheAssassin** [comment]
The signatures don't get used since there's no eco system to support them. Why embed a signature if there's no tools that can make use of it.

**Comment by antony-jr** [comment]
> Re. 1, OK, then let's add a check that this only gets deployed for GUI apps

@probonopd This is already in place, it just does nothing when the QApplication instance is not a subclass of QGuiApplication (this is done by dynamic cast , kind of).



> Works for me != license compliance... 

What is license compliance , is it similar to [software licensing audit](https://en.wikipedia.org/wiki/Software_licensing_audit)? 



> But this is surely an opt-in feature

I couldn't agree more.



> new license compliance complexity.

Again what does that mean.



>  all AppImage opt-in stuff never gets used (think signatures).

Are you talking about GPG signatures? If you are taking about GPG signatures then I think the reason its not used is because GPG signing is pretty complicated and most developers are not familiar with it, Also who wants to spend their time signing a software which has no warranty(As stated in license). **To contradict your statement, embedding update information and uploading the .zsync file is also opt-in but developers are starting to use it. So not all feature that are opt-in is not used.**

> The signatures don't get used since there's no eco system to support them. Why embed a signature if there's no tools that can make use of it.

Also for that reason.

**Comment by TheAssassin** [comment]
> @TheAssassin What is license compliance , is it similar to software licensing audit?

License compliance is the process of being *in complicance* with a license. If you follow all rules a license text requires you to obey, only then you have the rights the license grants to you and thus are compliant with it.

To illustrate this, let's pick a simple license, such as the [zlib license](https://en.wikipedia.org/wiki/Zlib_License). If you read through the text, there's three rules you *must* obey in order to gain some freedoms: you *must not misrepresent the origin of the software*, you *must mark altered versions of the software as such*, and *you must not remove or alter the license notice*.
If you follow these three rules, you may use the software *for any purpose, including commercial applications, ...*

If you follow the rules and use the software only in the ways the license permits you (which, for zlib, is pretty generous), then you are in compliance with the license.

A software compliance audit (or software licensing audit) is done to ensure you are in compliance with the licenses of all the software you use. It's an audit after all. License compliance however only describes the process of using software in compliance with their licenses.

I recommend you to get yourself informed on software licensing and compliance; you seem to have little knowledge, and that might get you into serious trouble. Using software without being compliant with its license is a copyright offense, and depending on your location and the location of the author can become expensive if not worse. Also, it's morally the right thing to be compliant with the licenses.

**Comment by probonopd** [comment]
For most open source licenses it mostly boils down to providing proper documentation along with the software itself, e.g., what Debian does in their copyright files. But yes, it's important to obey the licenses of the software that one distributes.

@TheAssassin wrote 

> it brings new license compliance complexity

I interpret this as "if we ship the updater along with the apps, then we must ensure that we honor the licenses of all the components we are shipping with the updater". The same is true for _any_ software one ships. Did you see anything in particular you are worried about @TheAssassin?

**Comment by antony-jr** [comment]
I patch(the source to patch is released under MIT) the QtXCB plugin which is licensed under LGPL(originally MIT)(see https://doc.qt.io/archives/qt-5.11/qtgui-attribution-xcb.html), We are only patching QtXCB sources which is part of Qt and not modify the source and not release it. All other plugins(AppImageUpdaterBridge and other bridges) are licensed under BSD because its not a derived work from any Qt sources. 

Now the BSD licensed plugins are loaded from QtXCB plugin itself(which uses the QtPluginInjector which is licensed under MIT).

So where do I violate Qt's license(LGPL or GPL), some pointers might be helpful.

So in general, every Qt application uses QtXCB plugin which is LGPL licensed and we only patch this plugin and release everything under the same LGPL license.

**Comment by TheAssassin** [comment]
I haven't said you do violate anything in particular. I'm not the copyright owner of any of the software you use at the moment (AFAICS), so I'm not in a position to sue you on anything. Nor am I a lawyer and can give profound legal advice. And after all, every decision would have to be made by a court in a lawsuit anyway.

My point is, you don't seem to be very educated about licenses and implications, from what I read so far. I am quite experienced nowadays, and am aware of all the cases where I act without license compliance. There's plenty, trust me.

The problems I have with any "auto bundling" stuff and this in particular is:

1. license compliance risks: you cannot be sure that the plugins shipped here can be used legally in combination with your own software (especially relevant when you use e.g., a commercial Qt license, and don't want to be obliged to the license terms of some random plugins; you're likely to run into issues there, and they're really really hard to understand for a companies' lawyers);
    - TL;DR: I as a software owner don't want my software to implicitly be linked with any random code "from the Internet", I can't necessarily see that there's more code in my software that I need to be aware of, my so-called "bill of materials" should NEVER change without me doing anything actively
2. this constant favoring "opt-out" for "opt-in": a simple "opt-in" with good documentation can mitigate the "incomplete bill of materials" problem mentioned in the previous argument
3. the plugin uses a lot of hacks and workaroundsp
4. I cannot ensure that a specific plugin `.so` file will work with my own Qt build
5. I think this is a build-time issue, not a packaging-time issue; a user should build the plugin against their own version of Qt and then later linuxdeploy-plugin-qt can pick it up

There's many more problems, I've mentioned enough of them. I don't want to keep having to explain basic license compliance, this is time consuming and I'm not a lawyer. You can trust me that my worries are eligible, I've been educated in recognizing such risks.

Shipping software can be problematic, with open source licenses (that follow the OSI specifications of open source) shipping binaries is not a problem at all. That's ensured by their standards.

Shipping **libraries** that are **autoloaded** however is a **really big issue**. You must make sure the software you ship doesn't apply any limitations on the software it's combined with.
However, you also need to look at the opposite way. Licenses of libraries you use in your own software might for instance prohibit their combination with the *autoloaded* software. There is virtually no way to automatically ensure this situation won't occur.

The only way to **reduce** the amount of issues with license compliance is for **you** to waive all your rights, in that case with most licenses (and for sure with open-source licenses as per the OSI definition) this is fine. Even a simple "you must credit my plugin in your software" means that if you auto-load it into other people's software, you **actively make them violate your license**, which is complete nonsense (and very likely wouldn't hold in a court; but still, it's not ok to bring anyone into such a situation in the first place).
However, even if you waive your rights, there is **no way to completely ensure there won't be problems**, you simply don't have any control about the software you auto-load into.

________________

I've thoroughly thought about the situation, and IMO it's a legal nightmare to auto-load stuff into other people's software. As unlikely the problems are, they might occur. And I don't want to be responsible for people getting issues with license compliance because I auto-load stuff into their software. We can easily write any disclaimers à la "I am not responsible" into our software licenses, but it's morally wrong to do anything we know is likely to lead to issues. The AppImage creators can be held liable, and copyright stuff can become *really* expensive.

Furthermore, I don't want to impose any weird update menu entries on people. I can recommend people to use it, but it's their decision and their free will shall be respected. They chose to build an AppImage, but they haven't chosen to make it updatable, nor have they chosen to include a graphical updater.

Sorry for this being a bit unstructured. It's late.

**Comment by antony-jr** [comment]
@TheAssassin Thank you for the information. :+1:  I think I understand now.
